In [1]:
import pandas as pd

In [4]:
path = f"/anvil/scratch/x-ylei3/RL-Index/RL_Index/data_preprocess/train_data/built_dataset/v2_train/train.parquet"
data_df = pd.read_parquet(path)
print(data_df.columns)

Index(['prompt', 'answer'], dtype='object')

In [5]:
data_df

,prompt,answer
0,"[{'role': 'system', 'content': ''}, {'role': '...","{""query"": ""\nWas there ever at any point in ti..."
1,"[{'role': 'system', 'content': ''}, {'role': '...","{""query"": ""\nIt might be a silly question, I d..."
2,"[{'role': 'system', 'content': ''}, {'role': '...","{""query"": ""\nIs there a way to get the list of..."
3,"[{'role': 'system', 'content': ''}, {'role': '...","{""query"": ""\nThe task\n\nGiven an array of int..."
4,"[{'role': 'system', 'content': ''}, {'role': '...","{""query"": ""\nFor most goods, we can compare th..."
...,...,...
30869,"[{'role': 'system', 'content': ''}, {'role': '...","{""query"": ""\nWe have a long protocol that we a..."
30870,"[{'role': 'system', 'content': ''}, {'role': '...","{""query"": ""\nI'm trying to solve the following..."
30871,"[{'role': 'system', 'content': ''}, {'role': '...","{""query"": ""\nWhat depth of soil is required fo..."
30872,"[{'role': 'system', 'content': ''}, {'role': '...","{""query"": ""\nIn the Krebs cycle, where do the ..."
30873,"[{'role': 'system', 'content': ''}, {'role': '...","{""query"": ""\n\nI would like to plot those two ..."

In [3]:
data_df

,query,pos
0,\nI'm new to the artificial intelligence field...,This is a fundamentally a philosophical questi...
1,\nSince a neutron and a proton are made up of ...,"A neutron is made of 3 quarks, two up quarks a..."
2,\nTo extend from the question things like goog...,Because not all programs require for their ope...
3,\nI want to test the hypothesis that a group o...,"<a href=""http://onlinelibrary.wiley.com/doi/10..."
4,"\nDarwin suggested that sexual selection, espe...",<strong>TL;DR</strong>: <ul><li>There is a dea...
...,...,...
30869,"\nIf I understand it right, correct term for s...","<a href=""https://www.mcafee.cc/Papers/PDF/Conc..."
30870,\nGood day\nI am currently implementing an aut...,The Raspberry Pi's UART interface can handle u...
30871,\nHow can I convert a sequence provided in a M...,"The <a href=""https://github.com/Edinburgh-Geno..."
30872,\nI have just started thinking about probabili...,<h1>Notes</h1><ul><li>I'd expect <code>arrange...
30873,\nWhich of these two theories is more accepted...,"The short answer is ""we can't."" The problem is..."